CREATE TABLE "Users" (
  "id_user" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" nvarchar,
  "img_link" nvarchar,
  "create_at" datetime DEFAULT (GETDATE()),
  "role" varchar(50),
  "hash_password" nvarchar(255),
  "status" varchar(20),
  "email" nvarchar(255) UNIQUE,
  "phone" nvarchar(20),
  "hash_tax_code" nvarchar(255),
  "ai_tier" int,
  "id_company" int
);

CREATE TABLE "Company" (
  "id_company" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" nvarchar(255),
  "company_tax_code" nvarchar(255)
);

CREATE TABLE "Transaction" (
  "id_transaction" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_subscription" int,
  "id_sponsor" int,
  "id_buyer" int,
  "status" nvarchar,
  "create_at" date,
  "invoice_date" date,
  "type" nvarchar
);

CREATE TABLE "Warehouse" (
  "id_warehouse" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_owner" int,
  "name" nvarchar,
  "address" nvarchar,
  "description" nvarchar,
  "location_address_text" nvarchar,
  "location_province" nvarchar,
  "location_commune" nvarchar,
  "location_long" double,
  "location_lat" double,
  "location_postal_code" nvarchar,
  "isSponsor" boolean,
  "sponsor_type" int,
  "status" nvarchar,
  "create_at" date,
  "update_at" date
);

CREATE TABLE "WarehouseImage" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_warehouse" int NOT NULL,
  "image_url" nvarchar NOT NULL,
  "is_thumbnail" boolean,
  "display_order" int
);

CREATE TABLE "WarehouseSection" (
  "id_section" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_warehouse" int,
  "label" nvarchar,
  "sector" int,
  "total_capacity" double,
  "available_capacity" double,
  "temp_min" double,
  "temp_max" double,
  "humidity" double,
  "hasCertification" boolean
);

CREATE TABLE "PriceTier" (
  "id_price_tier" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_warehouseSection" int,
  "label" nvarchar,
  "value" double,
  "unit" nvarchar,
  "area_unit" nvarchar
);

CREATE TABLE "CertificationSubmit" (
  "id_cerfSubmit" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "link" nvarchar,
  "isVerified" boolean,
  "id_type" int
);

CREATE TABLE "CertificationType" (
  "id_certification" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" nvarchar,
  "update" date,
  "law_references" nvarchar
);

CREATE TABLE "SponsorTier" (
  "id_SponsorTier" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "priority_level" int,
  "pricing_per_month" double,
  "year_pack_sale" double,
  "label" nvarchar,
  "update_at" nvarchar
);

CREATE TABLE "Rating" (
  "id_rating" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rate" double,
  "comment" nvarchar,
  "id_renter" int,
  "warehouse_id" int
);

CREATE TABLE "Bookmark" (
  "id_bookmark" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int,
  "id_warehouse" int
);

CREATE TABLE "AiConversations" (
  "id_ai_conversations" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" int,
  "criteria" json,
  "message" json,
  "total_input_tokens" int,
  "total_output_tokens" int,
  "create_at" date,
  "update_at" date
);

CREATE TABLE "AiSubscriptionTier" (
  "id_ai_subscription" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "label" nvarchar,
  "desciption" nvarchar,
  "token_input" int,
  "token_output" int,
  "price" double,
  "unit" nvarchar,
  "create_at" date,
  "update_at" date
);

CREATE TABLE "RentRequest" (
  "id_rentRequest" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_renter" int,
  "id_warehouse" int,
  "cargo_description" nvarchar,
  "other_detail" nvarchar,
  "duration" int,
  "duration_unit" nvarchar,
  "status" nvarchar,
  "renter_rejection_reason" nvarchar,
  "submit_at" date,
  "updated_at" date,
  "start_date" date,
  "end_date" date,
  "offered_price" double,
  "unit" nvarchar,
  "owner_note" string,
  "rejection_reason" nvarchar
);

CREATE TABLE "Contract" (
  "id_contract" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_owner" int,
  "id_renter" int,
  "id_rent_request" int,
  "cargo_description" nvarchar,
  "create_at" date,
  "status" nvarchar,
  "update_at" date,
  "start_at" date,
  "end_at" date,
  "cancel_reason" nvarchar,
  "payment_term" nvarchar,
  "penalty_clause" nvarchar,
  "special_term" nvarchar,
  "owner_legal_name" nvarchar,
  "owner_tax_code" nvarchar,
  "owner_email" nvarchar,
  "owner_phone" nvarchar,
  "owner_address" nvarchar,
  "renter_legal_name" nvarchar,
  "renter_tax_code" nvarchar,
  "renter_email" nvarchar,
  "renter_phone" nvarchar,
  "renter_address" nvarchar
);

CREATE TABLE "WarehouseCertification" (
  "id_warehouse" int NOT NULL,
  "id_cerfSubmit" int NOT NULL,
  PRIMARY KEY ("id_warehouse", "id_cerfSubmit")
);

CREATE TABLE "RentRequestDetail" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rentRequest" int NOT NULL,
  "id_section" int NOT NULL,
  "id_price_tier" int NOT NULL,
  "rented_area" double,
  "area_unit" nvarchar
);

ALTER TABLE "Users" ADD FOREIGN KEY ("ai_tier") REFERENCES "AiSubscriptionTier" ("id_ai_subscription") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Users" ADD FOREIGN KEY ("id_company") REFERENCES "Company" ("id_company") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("id_subscription") REFERENCES "AiSubscriptionTier" ("id_ai_subscription") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("id_sponsor") REFERENCES "SponsorTier" ("id_SponsorTier") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Transaction" ADD FOREIGN KEY ("id_buyer") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Warehouse" ADD FOREIGN KEY ("id_owner") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Warehouse" ADD FOREIGN KEY ("sponsor_type") REFERENCES "SponsorTier" ("id_SponsorTier") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WarehouseImage" ADD FOREIGN KEY ("id_warehouse") REFERENCES "Warehouse" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WarehouseSection" ADD FOREIGN KEY ("id_warehouse") REFERENCES "Warehouse" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "PriceTier" ADD FOREIGN KEY ("id_warehouseSection") REFERENCES "WarehouseSection" ("id_section") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CertificationSubmit" ADD FOREIGN KEY ("id_type") REFERENCES "CertificationType" ("id_certification") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rating" ADD FOREIGN KEY ("id_renter") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Rating" ADD FOREIGN KEY ("warehouse_id") REFERENCES "Warehouse" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Bookmark" ADD FOREIGN KEY ("id_user") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Bookmark" ADD FOREIGN KEY ("id_warehouse") REFERENCES "Warehouse" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "AiConversations" ADD FOREIGN KEY ("id_user") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RentRequest" ADD FOREIGN KEY ("id_renter") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RentRequest" ADD FOREIGN KEY ("id_warehouse") REFERENCES "Warehouse" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Contract" ADD FOREIGN KEY ("id_owner") REFERENCES "Users" ("id_user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Contract" ADD FOREIGN KEY ("id_renter") REFERENCES "RentRequest" ("id_renter") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Contract" ADD FOREIGN KEY ("id_rent_request") REFERENCES "RentRequest" ("id_rentRequest") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WarehouseCertification" ADD FOREIGN KEY ("id_warehouse") REFERENCES "Warehouse" ("id_warehouse") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WarehouseCertification" ADD FOREIGN KEY ("id_cerfSubmit") REFERENCES "CertificationSubmit" ("id_cerfSubmit") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RentRequestDetail" ADD FOREIGN KEY ("id_rentRequest") REFERENCES "RentRequest" ("id_rentRequest") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RentRequestDetail" ADD FOREIGN KEY ("id_section") REFERENCES "WarehouseSection" ("id_section") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "RentRequestDetail" ADD FOREIGN KEY ("id_price_tier") REFERENCES "PriceTier" ("id_price_tier") DEFERRABLE INITIALLY IMMEDIATE;
